version: '3.9'

services:
  frigate-wizard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frigate-wizard
    restart: unless-stopped
    ports:
      - "8080:80"
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
      - ./media:/media
    privileged: true
    environment:
      - NODE_ENV=production
      - API_PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  config:
  media:
